### ISSUE TITLE
Pypi package?

### ISSUE THREAD

**Issue by dannystaple** [orionrobots/ldraw-to-scad#13]
Support the `pip install ldraw-to-scad` (might need to snake case that) invocation.

**Comment by schiele** [comment]
Currently WIP in pypi branch.

**Comment by schiele** [comment]
See the current test package at https://test.pypi.org/project/ldraw-to-scad/.

**Comment by dannystaple** [comment]
That looks good. I’ll have to wait to have access to a machine that doesn’t have this (I’m on vacation), but the package metadata makes sense to me.

On 20 May 2022, at 07:30, Robert Schiele ***@***.******@***.***>> wrote:



See the current test package at https://test.pypi.org/project/ldraw-to-scad/.

**Comment by schiele** [comment]
Released: https://pypi.org/project/ldraw-to-scad/
